project: 
  type: website
  
website: 
  page-navigation: true
  title: "NMFS Openscapes" 
  site-url: "https://nmfs-openscapes.github.io" 
  repo-url: https://github.com/nmfs-openscapes/nmfs-openscapes.github.io
  repo-actions: [edit, source, issue]
  favicon: images/openscapes_hex.png  
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/logo-transparent-crop.png"
    favicon: images/openscapes_hex.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/nmfs-openscapes
        text: "NMFS Openscapes"
      - icon: mastodon
        href: https://fosstodon.org/@openscapes
        text: "Openscapes Mastodon"
      # bluesky icon not yet available (in my installation)
      # - icon: bluesky
      #   href: https://bsky.app/profile/openscapes.bsky.social
      #   text: "Openscapes Bluesky"            

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about-openscapes.qmd
        text: About Openscapes
      - href: about-nmfs-openscapes.qmd
        text: About NMFS Openscapes
      - section: mentors/index.qmd
        text: Mentors Community
        contents: 
          - href: mentors/activities.qmd
            text: Current Activities  
          - href: mentors/activities.html#previous-activities
            text: Previous activities
          - href: mentors/mentor-calls.qmd
            text: Mentor Calls Skills            
      - href: champions.qmd
        text: Champions Program      
      - section: cohorts/index.qmd
        text: Champions Cohorts
        contents: 
          - cohorts/NMFS-fall2024.qmd  
          - cohorts/NMFS-fall2022.md 
          - cohorts/SEFSC-sum2022.md 
          - cohorts/AFSC-win2021.md 
          - cohorts/FDD-fall2021.md
          - cohorts/NMFS-fall2021.md
          - cohorts/NEFSC-spr2020.md            
      - href: data-academy.qmd
        text: Data Academy
      - href: media.qmd
        text: Presentations and Media
      - resources.qmd  
      - href: blog.qmd
        text: Blog
      - contact.qmd         
      - href: coworking-opportunities.qmd
        text: Live Coworking

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
