---
title: "Openscapes Champions Program"
---

The NOAA Fisheries Openscapes Mentor Community will lead 3 Champions Cohorts in Fall 2026! Read on to learn what this is and read past [cohort pages](/cohorts) to learn stories of what participants have accomplished.

**Fall 2026 theme: Making your work and processes understandable, transferable, and open** ([theme details in FAQ below](#sec-2026-theme) <!---; [info session slides](https://docs.google.com/presentation/d/1SW_EBcxcD8ZHDXANucBcF-K5f-E1IR5OpVnWJmIAvHE/edit?slide=id.g3720335bad7_1_989#slide=id.g3720335bad7_1_989)--->). We encourage teams or individuals interested in this theme to sign up. You do not need to be interested in the theme to apply. Please sign up whether or not the theme resonates with you now.

<!--- \[Sample email to share announcement\] (TODO). --->

## Sign up for Fall 2026

**Sign up by Sept 8, 2026, COB (close of business) in your time zone via [this Google Spreadsheet](https://docs.google.com/spreadsheets/d/1hLmrrvajZb9yR8Vt8ngUPp4wdCeBeYjFBxb02OvX4nU/)**. We will confirm participation via email by Sept 10.

Please indicate the Cohort date-times you are available. You can sign up individually or with a colleague or team (enter everyone's name on a separate line).

## What is the Champions Program?

**This is an opportunity to make your work and processes understandable, transferable, and open — and strengthen connections with colleagues**

Since 2020, the Openscapes Champions Program has helped over 600 NOAA Fisheries staff make substantial progress on difficult workflow transformation goals and strengthen connections across NOAA Fisheries. Goals from previous teams and individuals include transitioning to new cloud computing or data storage workflows, improving team awareness and collaboration, fostering and teaching team learning techniques, documenting standard operating procedures to onboard and offboard staff, and automating (scripting) large data-heavy reports.

Openscapes Champions is a remote-by-design, cohort-based mentorship program that helps teams re-imagine data analysis and stewardship as a collaborative effort, develop modern skills that are of immediate value to them, and cultivate collaborative and inclusive communities. It is focused on open science and data modernization via biweekly curriculum that Openscapes has improved over 30 Cohorts 2019-2026. The goal is strengthening a teaching and learning culture within teams and organizations. This program is not only for scientists: admin, IT staff, and beyond are welcomed. Individuals and teams need not have familiarity or expertise in open science, data science, or coding, to benefit from the Openscapes Champions Program.

Come join us and make progress on new tasks or big goals that can be hard to get traction on by working in facilitated sessions with your peers and the Openscapes team. [Scroll the blogs](blog.qmd#category=champions) on what NOAA Fisheries teams and individuals have accomplished in the 16 NOAA Fisheries Champions Cohorts over the past 5 years.

```{=html}
<!--- Through Openscapes cohorts, you focus on your own work with your peers or a team. As the program introduces modern concepts, tooling, and examples from your peers for collaborative open data science, groups focus on where you are and where you want to go together. **Openscapes Champions is "not your traditional training/workshop" because teams:**

-   Have real-world experiential learning: developing psychological safety and habits for implementing change
-   Learn together and get unstuck: Identify and make progress on barriers as Openscapes introduces modern concepts, tooling, and examples from peers
-   Work on what is important to them, often something hard to do. Something they want to change.
--->
```

## Champions Program Details

**Fall NOAA Fisheries Openscapes Champions Cohorts run from September-November 2026!** We will meet as a cohort five times over two months, on alternating weeks, with additional optional coworking times.

- **Date-Times**:

  - **Cohort-A: Sep 22, Oct 6, 20, Nov 3, 17.** Tuesdays 1:00 - 2:30pm PT.

  - **Cohort-B: Sep 23, Oct 7, 21, Nov 4, 18.** Wednesdays 10:00 - 11:30am PT.

  - **Cohort-C: Sep 23, Oct 7, 21, Nov 4, 18.** Wednesdays 1:00 - 2:30pm PT.

  - **Coworking** for all cohorts (optional): Sep 29, Oct 13, 27, Nov 10. Tuesdays 12:00 - 1:30pm PT.

- **Where:** remotely, via Zoom (from your browser, no install needed)

- **What we learn:** [Champions program core lessons](https://openscapes.github.io/series), with NOAA Fisheries examples.

- **Cost:** Free; this opportunity is supported by NOAA funding to Openscapes.

- **Expected time commitment:** 8hrs/month for 2 months is a minimum expected time commitment. This accounts for 3 hours/month of synchronous Cohort Calls, optional Coworking hours, and group Seaside Chats where you plan and implement changes to how you work.

- **Who:** Anyone interested in improving their data science workflows. FTEs and Affiliates from any Fisheries Science Center, Regional Office, or HQ Office are welcome to participate. This program is not only for scientists: admin, IT staff, and beyond are welcomed. We aim to remove barriers to outside collaboration. It is important that those who participate can do so in all or most sessions, and are energized to be interacting with like-minded individuals across NOAA Fisheries. Sign up to participate individually, with a colleague, or your team.

## "Ask Us Anything" info sessions

**Are you curious about participating in the Champions Program** and want to learn more? We give talks to many audiences and standing meetings (details in table below). Anyone is welcome to attend.

**Are you a NMFS Openscapes Mentor or past Champion?** Consider giving a talk at your Center/Regional Office (talk/brown-bag, 5 mins at All Hands). Please add sessions to [Sign up sheet, 'Talks, AMA Schedule'](https://docs.google.com/spreadsheets/d/1hLmrrvajZb9yR8Vt8ngUPp4wdCeBeYjFBxb02OvX4nU/edit?gid=1423956583#gid=1423956583) tab and to the NMFS Open Science Google Calendar so others can find them. <!--- Here are [slides](https://docs.google.com/presentation/d/1SW_EBcxcD8ZHDXANucBcF-K5f-E1IR5OpVnWJmIAvHE/edit?slide=id.g3723cbac770_1_6#slide=id.g3723cbac770_1_6) introducing the Fall 2026 Champions Program with background information we can all use to present. --->

**Table.** Center / Office info sessions. To join an info session below, find Google Meet links in this [Sign up sheet, 'Talks, AMA Schedule'](https://docs.google.com/spreadsheets/d/1hLmrrvajZb9yR8Vt8ngUPp4wdCeBeYjFBxb02OvX4nU/edit?gid=1423956583#gid=1423956583) tab or in the NMFS Open Science Google Calendar.

|  |  |  |  |  |  |
|------------|------------|------------|------------|------------|------------|
| **Date** | **Time** | **Center/Office** | **Event info name / length** | **Point person** | **Speaker** |
| 2026-07-09 | 1:00pm ET/10:00am PT |  | 5 min in RITC weekly meeting | Evan Nightingale | Eli Holmes |
| 2026-07-15 | 3:30pm ET/12:30pm PT |  | 5 min in Fisheries Data Governance committee meeting | Lisa Peterson | Lisa Peterson |
| 2026-07-16 | 3:30pm ET/12:30pm PT |  | 5 min in FIS Program Management Team meeting | Lisa Peterson | Loren Stearman |
| 2026-07-29 | 3:00pm ET/Noon PT |  | 5 min in Coder PSG meeting | Lisa Peterson | Lisa Peterson |
| 2026-08-17 | 2:00pm ET/11:00am PT |  | AMA / 1 hr | Julie Lowndes, Eli Holmes | Julie Lowndes, Eli Holmes |

```{=html}
<!--- ## Attend an "Ask Us Anything" info session

To share about the opportunity, our goal in September is to give a talk at each Center/Regional Office. Here are [slides introducing the Fall 2024 Champions Program](https://docs.google.com/presentation/d/1a_nDKAxpvaWURITBm_HiDvzCd7GLDmb8ooi-d0dRI5I/edit?usp=sharing) with background information we can all use to present.

**Table.** Center / Office info sessions.

**To join an info session below, find Google Meet links in this [Google Sheet](https://docs.google.com/spreadsheets/d/10zTz6i-ZuwnQhCTG63jRku0BtVwgc9e1tqnfGuiyM2c/edit?gid=1423956583#gid=1423956583)** or in the NMFS Open Science Google Calendar.

|            |                           |                   |                                        |                                    |                           |     |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| **Date**   | **Time**                  | **Center/Office** | **Event info name / length**           | **Mentor/Point person**            | **Speaker**               |     |
| 2024-08-29 | 2:30 pm PT                | SWFSC             | SWFSC Openscapes info session / 20 min | Lynn DeWitt, Heather Nicholas      | Eli Holmes, Julie Lowndes |     |
| 2024-09-04 | 9:00 am HT / 12:00 pm PT  | PIFSC             | PIFSC Openscapes Q&A / 50 min          | Amanda Bradford                    | Eli Holmes, Julie Lowndes |     |
| 2024-09-04 | 1:30 pm PT                | NWFSC             | NWFSC Openscapes Q&A / 30 min          | Eli Holmes                         | Eli Holmes, Julie Lowndes |     |
| 2024-09-05 | 11:00 am PT               | All               | NMFS Openscapes Q&A / 50 min           | Eli Holmes                         | Eli Holmes, Julie Lowndes |     |
| 2024-09-05 | 3:00 pm ET / 12:00 pm PT  | SEFSC             | SEFSC Openscapes info session / 50 min | Ana Vaz, Molly Stevens, Adyan Rios | Eli Holmes, Julie Lowndes |     |
| 2024-09-10 | 9:00 am AT / 10:00 am PT  | AFSC              | AFSC Openscapes info session / 45 min  | Eli Holmes                         | Eli Holmes, Julie Lowndes |     |
| 2024-09-12 | 1:00 pm AT / 2:00 pm PT   | AFSC              | AFSC Openscapes info session / 45 min  | Eli Holmes                         | Eli Holmes, Julie Lowndes |     |
| 2024-09-11 | 12:00 pm PT               | All               | NMFS Openscapes Q&A / 50 min           | Eli Holmes                         | Eli Holmes, Julie Lowndes |     |
| 2024-09-13 | 11:00 am AT / 12:00 pm PT | AKRO              | AKRO Openscapes Q&A / 50 min           | Craig Millard                      | Eli Holmes, Julie Lowndes |     |

### How to request a “Why Openscapes” talk & AMA

Want help encouraging your colleagues to sign up? To request a presentation & AMA, select a time from Eli’s calendar and add Julie (julia at openscapes.org) and Stefanie (stefanie at openscapes.org). Eli has cleared Sept 2-14 for giving these presentations.

Please add sessions to [Sign up sheet, 'Talks, AMA Schedule'](https://docs.google.com/spreadsheets/d/10zTz6i-ZuwnQhCTG63jRku0BtVwgc9e1tqnfGuiyM2c/edit?gid=1423956583#gid=1423956583) tab and to the NMFS Open Science Google Calendar so others can find it. Stef will add them to the following table.
 --->
```

## FAQ - Frequently Asked Questions

### What is the theme for the 2026 cohorts? {#sec-2026-theme}

The NOAA Fisheries Openscapes Champions Cohorts’ theme for 2026 is **“Making your work and processes understandable, transferable, and open”**. These Cohorts are about creating workflows that are more accessible to your entire team, and giving you dedicated time to invest in habits to make this easier. We welcome anyone to participate, whether or not you are interested in this theme, and whether you join as an individual or with others. This opportunity is open to all staff and affiliates, across all job titles, at no cost to your staff. There are no prerequisites. As a participant, you may be someone:

- **Onboarding to a new role or position** and interested in developing an open science mindset and connecting to people in similar situations at NOAA Fisheries.

- **Offboarding from your projects** and wanting to honor that work and legacy by documenting and sharing your processes for others to take on.

- **Documenting your IT or procurement workflows** since these underpin all projects and can be a way to connect and streamline processes.

- **Transitioning to cloud workflows** and wanting to learn how others approach data and workflow optimization, project management, and refactoring.

- **Supporting your staff or team** as they transition their processes and wanting to better understand how they work and their needs.

### What does the theme mean for the cohorts? Will the lessons change in any way?

We will be teaching the Champions core lessons and some will be tailored to help people think through what this year’s theme might mean for their own work. Participants will use the [Pathways sheet](https://openscapes.github.io/series/pathways.html#pathways-concept) to take stock of their workflows, and as always we expect and will teach to a wide range of skills and levels of experience.

### What is a team?

> How you define 'team' is completely up to you and having one person be in the cohort and using in-between session 'seaside chats' to bring back the information to another group is 100% fine. That is common in the cohorts. In my first Openscapes cohort, I was the only person from my project. My personal goal was to use the Openscapes structure to help a team that I am on figure out how to tackle some off-boarding tasks due to a retirement. During my second cohort, there were 2 team members in the cohort and 2 not in the cohort. We focused on standardizing our data to get ready for our GitHub served data package. For the 3rd cohort I am doing, 2⁄3 of our team is in the cohort as we start to get organized for a major revamp of our report into a reproducible workflow. - **Eli Holmes (NMFS Open Science, NWFSC, NMFS Openscapes)**

Teams do not need to be a formal research group; they can be collaborating in other ways. Team members do not all need to have technical or data interests, but share a curiosity and interest in improving something about how they work.

### What if I don’t have a team?

That’s ok, please sign up! We’ll help you connect with participants who share some of your goals or needs.

### If a team is participating together, how important is it for them all to be in the same cohort?

Not too important. Sometimes people feel more 'connected' if they see people they know in the virtual room. The activities during the cohort calls are not by 'team'; they are in random breakout groups. Participants are expected to have ‘Seaside Chats’ together with their teams in the weeks between Cohort Calls. It’s more important that participants are committed to attending all sessions in the time slot they have chosen.

### Can I sign up if I have participated in a previous Openscapes Champions Cohort?

Yes. If Cohorts are oversubscribed, this would be discussed by a small selection committee.

See [Frequently Asked Questions](https://openscapes.github.io/series/what-to-expect.html#teams-faqs) on the main Openscapes site for more guidance.

## Stories from past participants

### Cloud migration and data preservation progress happens with collaboration.

As NOAA is migrating data to the cloud, this means many people are needing to change their workflows. One exciting example of something that wasn’t possible before is the [NOAA Fisheries Cloud Computing Setup](https://github.com/nmfs-opensci/CloudComputingSetup/) documentation that NOAA Fisheries Openscapes Mentor Molly Stevens (SEFSC) started in preparation for the Champions Cohort (following six months of [collaborative testing](https://github.com/orgs/nmfs-openscapes/projects/46/views/6?filterQuery=workstation&pane=issue&itemId=102920703&issue=nmfs-openscapes%7Chow-we-work%7C33) with other Mentors). When Alex Norelli learned about it while participating in the Champions Cohort, she found this setup resource valuable for her own work. She began collaborating with Molly to test it, achieving something she could not do before the Cohort started:

> “I benchmarked different cloud environments and explored data management solutions like Google Cloud Buckets, which sparked so many seaside chats about best practices in migrating current workflows to the cloud.” - **Alex Norelli, SEFSC**

Ultimately, Alex co-led a Google Workstations Clinic during the last weeks of the Cohort with Molly and Jon Peake (NMFS Open Science), which benefitted additional participants and helped further develop the documentation. This example embodies how change happens within organizations: people are able to do more together than they can alone. And it starts with the practice of creating something useful for others, sharing it early, and iterating together.

Read more in the [Fall 2025 Champions Recap](https://openscapes.org/blog/2026-02-26-nmfs-champions-2025/).

### [Open Science Momentum at NOAA Fisheries](https://www.fisheries.noaa.gov/science-blog/open-science-momentum-noaa-fisheries), 2025, by the NMFS Openscapes Mentors.

> "I've already seen Openscapes change how NOAA Fisheries is doing things. There's a national peer network for learning, getting help, sharing tools, fixing things, and innovating. I see this continuing to grow as the community grows and people see what's possible. The emphasis on open, reproducible science will make it easier for partners and the public to engage in our work. Openscapes is contributing momentum to implementing tools that we need to do our jobs better." – **Phoebe Woodworth-Jefcoats, PIFSC**

### Kourtney Burger, Biological Science Technician, SWFSC Acoustic Ecology Lab.

Kourtney participated in a PIFSC-SWFSC Cohort in Fall 2022. She shared her experience in a post for the NOAA Fisheries blog: [Sound Bytes: Championing Open Science](https://www.fisheries.noaa.gov/science-blog/sound-bytes-championing-open-science). In it, Kourtney describes how she transferred a field methods manual from a set of disparate files on Google Drive to a [Quarto web book on GitHub](https://sael-swfsc.github.io/adrift-field-methods/).

> “Seaside Chats with our SAEL team allowed those of us attending the Openscapes workshop to share our newfound knowledge and experience so we could make our science more open. During these sessions, we streamlined our science pathways, documented our methods through GitHub, and had general team strategy discussions.” - **Kourtney Burger, SWFSC**

### Marine Mammal Laboratory (MML) Stock Assessment Report team from AFSC.

Rod Towell, Nancy Young, Tony Orr, Erin Richmond, and Brian Fadely participated in an Openscapes Champions Cohort in Winter 2022 and shared the story of the impact on their reporting and team culture (13-min [recording](https://youtu.be/whC4FyHuVg8) \| [slides](https://docs.google.com/presentation/d/16oScbiL9cXvcUZCpsquc39csq0SbP6vSX3CJ6L4wc7w/) with detailed notes).

> "Learning WITH each other, FROM each and FOR each other" **- Rod Towell, AFSC**

Impetus - SAR process is overwhelming and inefficient.

- Annual process with overlap between years 
- Large project: \>400 pages
- Multiple authors, collaborators, and internal/external reviewers 
- Version control issues
- No easy way to track discussions, decisions, ideas for future years
- No cohesive or formalized on/off-boarding, protocols

MML SAR Team goals

- Reframe SAR development as a collaborative effort
- Incorporate new tools but meet staff where they are
- Maintain consistency with NOAA Fisheries SAR approach

Reflections

- Motivated team, commitment, endurance, good communication and collaboration 
- This is a fluid, adaptive and dynamic process
- Used skills and problem-solving processes learned from Openscapes; the status quo was not acceptable so change was necessary
- Change is incremental - it doesn't have to happen all at once!
- Time, energy, commitment -\> Reward!

### A Year of Open Science Community Building at NOAA Fisheries

Lightning talks for the Year of Open Science Culminating Conference, March 21, 2024 ([recording](https://youtu.be/n1VaV8f6qQE) \| [slides](https://docs.google.com/presentation/d/1xR0UyplIJbTJQmog8tx2OKNi6jeK7LvegJq5vai5Y2k/)). Eli Holmes (NOAA Fisheries Open Science), Evan Howell (Director of the Office of Science and Technology), Megsie Siple (Alaska Fisheries Science Center), Amanda Bradford (Pacific Islands Fisheries Science Center), Brian Fadely (Alaska Fisheries Science Center Marine Mammal Stock Assessments), Vivian Matter (Branch Chief of Southeast Fisheries Science Center), Kathryn Doering (Office of Science and Technology), Christine Stawitz (Office of Science and Technology), Carissa Geravsi (Gulf of Mexico Integrated Ecosystem Assessment), Lynn Dewitt (California Current Ecosystem Assessment Team).

## Mentor roles

The growing [NMFS Openscapes Mentor community](/mentors/) — staff from across NOAA Fisheries interested in supporting others with teamwork and open science — will be increasingly involved with Champions Cohorts, and point-people for questions about what is involved and how to sign up. Mentors play different roles during different phases of Champions Cohorts.

<!--- **Pre-cohort engagement:** Mentors are empowered to encourage their colleagues to sign up for Openscapes Champions Cohorts. The Openscapes team will support you in **giving a talk at your Center/Regional Office** (talk/brown-bag, 5 mins at All-Hands). When you have something scheduled, please add sessions to [Sign up sheet, 'Talks, AMA Schedule'](https://docs.google.com/spreadsheets/d/1fpMJpReMuAW3W_U7rGSBkM1BgzWdVySLqLec-xoZYUc/edit?gid=1241468325#gid=1241468325) tab and to the NMFS Open Science Google Calendar so others can find them. Here are [slides](https://docs.google.com/presentation/d/1Q6zerBOYfSr-Sw0YTz2JV8OOskjw_0oGOIM2WSMmS84/) introducing the Fall 2025 Champions Program with background information we can all use to present. --->

**During cohort:** Mentors participate in the Champions Program (in fact, Champions cohorts are scheduled as "takeovers" of regular Mentors calls to be mindful of Mentors' time commitments). Here are several roles where Mentors can contribute:

- Meta-listeners (role model psychological safety, live notetaking; review [2023 Mentor skills](/mentors/mentor-calls.html) we developed; contribute to 20-min post-cohort debriefs as you can to help surface ideas and set direction (stay in Zoom after the Cohort calls)
- Content experts (responsive during Cohorts Calls, Seaside Chats, Coworking to help Champions with their goals)
- Helpers (during Coworking / Seaside Chats, screensharing to fix merge conflicts, add documentation)
- Participants (learn with your team as a Champion, focus on your work in Seaside Chats and Coworking)
- Teachers (teaching specific Champions lessons, pre-arranged)

```{=html}
<!--- ## Selection and how to participate

*This is the 2024 selection process; we will iterate in 2025*

**In 2024, we selected participants for the 3 Cohorts with transparent decision criteria co-designed with the NMFS Mentors** (see below), knowing that with 194 total signups for 120 seats (which is fantastic!), there is no one perfect way to select. Openscapes is about workflows shifts and movement building, and the Champions Program is designed with intentional structure to balance specific roles/boundaries while also being lightweight/reduced process so you all can focus on your science.

Openscapes will remain strict to the 40 participants per Cohort for the 5 synchronous Cohort Calls with no "drop ins" or "shadowing"– this is by design for active engagement (Champions Calls are not webinars where you sit back) and to build psychological safety within the group (being safe to be vulnerable is part of learning). We balance openness with trust building; we share all lessons and slide decks via the [Champions Lesson Series](https://openscapes.github.io/series), but we do not share the call agendas with live notes outside of the Cohort.

**Seaside Chats are the way for people outside the Cohort to participate.** Part of the Champions program design is that participants have “Seaside Chats” in the off-weeks during the 2 months, where they focus on applying what they learned into their own work and include other colleagues or team members. In many cases, not all team members who signed up will be selected to participate in the 5 Cohort Calls. These will be organized and led by the Champions using guidance from Openscapes, and there is no “prework” to attend.

### Decision criteria for 2024 Program

*We will reuse and build on this criteria for the 2025 program.*

We selected the Cohorts with transparent decision criteria that were developed with the Mentors, Eli Holmes, and the Openscapes team.

We prioritized participation by:

-   People who committed to a Cohort date-time by marking "Yes" in the spreadsheet
-   People who have not previously participated in an Openscapes Champions Cohort
-   Strategic Initiative groups: Passive Acoustics (PAM), Active Acoustics (AA), Climate and Fisheries (FDD). Genomics ('omics).
-   Office that has never participated or participated little: OPR, OST, NEFSC, AKRO, GARFO
-   New hires
-   Teams with NOAA staff
-   Caps on count totals across Centers: High: no more than 18 participants per division; Low: if \< 5 signed up for one Center, accept all.

Criteria that did NOT affect selection:

-   People who signed up as individuals or as part of a team were considered equally;
-   Date of signup.

Waitlist decisions:

-   If people declined, we selected people from the waitlist, prioritizing same cohort, same division, not participated before, same team, availability for Cohort date-time. --->
```
