---
title: "Current Activities"
---

### 2025 Mentors Community

-   **Mentor Calls** (Wednesdays, biweekly):
    -   **January:** visioning and goal-setting.
    -   **February - April: [Winter 2025 Group Coaching] takeover!**
    -   **April:** co-designed and responsive to groups’ goals and needs.
    -   **May - June:** Standup, “What are you working on now, what are you stuck on, what is a big focus over the next 2 weeks?”
    -   Summer break
-   **Coworking** (Tuesdays, weekly):
    -   Work on your goals! Coworking sessions by design have no agenda, are self-organizing and work-focused. They are less about "big ideas for discussion". They work best when a few people show up with concrete things to accomplish or work on, and we get quickly into breakout rooms to cowork on these ideas. 
    -   When you show up, these are some of the specific things that you can do: 
        -   Work on your own code, writing
        -   Ask for feedback on something
        -   Review Mentor Calls, practice skills with someone
-   **In-person** [Summer 2025 Workshop], July 21 in Seattle
-   **ESIP Summer conference,** July 22-25 in Seattle - cross-government open data science folks
-   **NMFS Openscapes Champions Cohorts** ([Mentor roles](https://nmfs-openscapes.github.io/champions.html#mentor-roles) in pre-cohort engagement, and mentoring during cohorts, October - December).

### Summer 2025 Workshop {data-link="Winter 2025 Group Coaching"}

The NOAA Fisheries Openscapes Mentors Summer Workshop is July 21. A hybrid event across timezones from Hawaii to the East Coast.

-   **Purpose:** Have new opportunities for co-creation across our centers/offices, and amplifying our work since it is of great use for others.
-   **Outcomes:**
    -   Increased Mentors’ awareness across projects and progress on new ideas and barriers;
    -   Blog post following Summer Workshop highlighting Mentors’ work;
    -   More examples for impact and shared slides.
- **Process:** A facilitated workshop with some plenary learning time and Mentors deciding what you want to work on and share.

### Winter 2025 Group Coaching

The NOAA Fisheries Openscapes Mentors Winter 2025 skillbuilding activities to become better mentors and team leaders. The "Mentoring with a Coach Approach" will be a 5-session Mentor Calls takeover Wednesdays 1:00-2:30 pm PT on February 12, 26, March 12, 26, and April 9.

## Previous Activities

### Summer-Fall 2024

To kick off Mentors activities, we will focus on preparing for and leading three fall Champions Cohorts. Immediate activities will include scheduling and communicating the opportunity with colleagues, including sending emails, giving talks, ask-me-anythings, and helping folks sign up.

[Kickoff slides](https://docs.google.com/presentation/d/1a_nDKAxpvaWURITBm_HiDvzCd7GLDmb8ooi-d0dRI5I/edit#slide=id.g28f9ffc64ff_0_0)

### October-December 2023: NMFS Mentors Cohort!

```{=html}
<!--- **Please join us: nominate yourself in [this Google Form](https://forms.gle/LJF9gTZCX7ThTzSm9) by Sept 23!**   
**["Is this for me?" 5-min slides](https://docs.google.com/presentation/d/1cSLanri2GM_zKYgI4MzzSdwN1U6WIm01atInGeohTJw/edit?usp=sharing)** --->
```

Through facilitation and practical training for mentoring, teaching, and coaching, Openscapes will help NMFS mentors strengthen skills and strategies to support colleagues with diverse comfort levels with software, coding, and data, while also strengthening relationships across centers/offices. Through this, mentors will identify and co-create on common resources and activities – such as code or databases for identical tasks or community developed standard practices – so there is less reinventing at each center.

The FY24 mentor cohort will start with a mentors-only Openscapes Champions cohort (facilated bi-weekly group meetings) during which Openscapes will guide the mentor cohort in discussing the needs and challenges for adoption of Open Science in NMFS and to develop actions to take. The facilitated meeting are vitual and twice monthly. Mentors will also collaborate asynchronously (e.g. Google Chat, GitHub). During the fall session, mentors will learn and practice coaching and mentoring skills in preparation for the winter Champions cohorts. We will also start identifying cross-center roadblocks that mentors can collaborate on throughout the next years.

#### Timeline & topics {#sec-timeline}

-   **Dates: Twice monthly starting October 17, 2023**
-   **Times: 12:00 - 1:30pm PT / 3:00 - 4:30 pm ET** \< note revised time
-   **Location: Remotely, via Google Meet**

#### Mentor Calls

**Mentor Calls** are when we convene as a group to learn and plan. Agendas are accessible to Cohort participants in our [Cohort Google Folder](https://drive.google.com/drive/folders/1eL0OnwySgTjcI_J6iI0NR8BgiqG0jB9V?usp=sharing); they are also an archive of our live notetaking. See [Mentor Calls Skills](mentor-calls.qmd) for details.

| Date | Mentor Call Topics |
|-----------------|-------------------------------------------------------|
| 10/17 | 1\. Openscapes mindset for mentors: What does it mean to be a mentor? What does Open Science at NMFS mean? <!-- Julie is point --> |
| 10/31 | 2\. Developing strong Open and Collaborative Communities <!--Stef is point: Stef Butland on the rOpenSci and rLadies --> |
| 11/14 | 3\. The art of teaching skills: running GitHub clinics <!-- Eli is point: 5 min on the Women in Data Sci GitHub clinic; triads on talk, show, do ---> |
| 11/28 | 4\. Supporting teams to tackle workflow change through the Champions Program <!--- Facilitating discussions and developing team culture  Julie is point: lecture on the Openscapes method of facilitating discussions)? ---> |
| 12/12 | 5\. Reflections and shaping future plans <!-- Julie is point: Guest Alexis Hunzinger --> |

##### Seaside Chats

**Seaside Chats** are for small-group coworking in weeks alternating between Mentor Calls. Topics are to reflect with your other center mentors in-between cross-center cohort calls. Note particants from different centers or offices can have Seaside chats together. We will organize our Seaside chats after the first mentor calls.

| Date | Seaside co-working sessions |
|------------------|------------------------------------------------------|
| Week of 10/23 | Begin work on an Open Science Pathway for your center, office or program. Where are you at? Where would you like to be? Do you have the info you need to answer this? |
| Week of 11/6 | Keep working Open Science Pathway for your center, office or program with specific discussions of needs/challenges |
| Week of 11/20 | Cross-FMC discussions of Open Science Pathways and work on shared organizing with GitHub |
| Week of 12/4. | Discuss ideas and plans for coordinating & engaging staff in Open Science goals |

### January-June 2023

From January-May through our bi-weekly meetings we are learning coaching and mentoring skills. We are learning valuable coaching skills - how to ask open-ended questions, how to listen - that make us better equipped as mentors, teachers, and leaders. When listening as a coach, we're trying to help the other person define their problem and find their solution, outside of our expertise. This is different from mentoring, when we do have an answer within our expertise. Developing these coach listening skills, what questions to ask, and when to use mentoring vs coaching skills, is the focus of our sessions; we are practicing coaching skills together to tackle common challenges and skill-build together.

Our mentor-coach sessions are cross-government, and include other Openscapes mentors working within and across their own institutions.

### 2022 July-August

The NMFS Openscapes mentor group is meeting bi-weekly. Current focus is on activities surrounding the summer cohorts at SEFSC and Cal EPA.

### 2022 Spring

Mentors and other interested folks across science centers and regional offices met several times to plan and give presentations about NMFS Openscapes efforts to individual science centers and the NMFS Science Board.

### 2022 January-March

The AFSC Mentors met bi-weekly during the 2021-2022 AFSC cohort.
