---
title: "NMFS Openscapes Mentor Community"
---

The NMFS Openscapes Mentor program supports local Open Science leaders within the NOAA Fisheries offices (science centers, regional offices and headquarters). The program provides leadership, coaching, and skill-building training to help mentors become better local leaders and to support their Open Science goals for the coming year. In addition, the program helps mentors network across NOAA Fisheries with others with similar goals and with the Openscapes community at other federal agencies.

**The program helps mentors carve out time to make steady progress on their goals** and to support their learning journeys. Mentors meet each week to move their work forward together through Mentor Calls and Coworking sessions. What’s your big goal or project that can get off the ground or make happen together? What are you trying to make a success? Do you see a roadblock that shouldn’t be? Working together, mentors have been able to realize organization change goals—such as delivering workshops, getting new training, developing NMFS-wide resources like GitHub Enterprise, documenting Google Cloud Workstations, and building healthy team cultures.

**The mentors are also local representatives for NOAA Fisheries Open Science**, including Open Data, Open Source and Open Collaboration. According to their interest and capacity, they help design and promote in the Openscapes fall Champions cohorts, spearhead communication with with their local leadership, act as a point-person for interested local staff, help identify local needs, and help communicate, or potentially organize, teaching resources for their local staff. The mentor group is modeled after the [NASA Openscapes Framework approach](#0).

**Participation is year-long and includes [a cycle of activities](https://nmfs-openscapes.github.io/mentors/activities.html#mentors-community).** Jan-May is focused on the mentors: they define their goals and activities, participate in skill-building training alongside mentors from across Openscapes communities, and [engage in active work](https://github.com/orgs/nmfs-openscapes/projects/46) on actualizing their goals. In late summer, mentors help plan the fall Champions cohorts (120 staff across the agency) which run Oct-Dec. Mentors do not meet as a group Oct-Dec. Those who want to participate in the Champions cohorts will do so while others will work on their goals independently.

## Activities

See our current and previous [activities](activities.qmd)!

## Co-leads:

-   Julie Lowndes and Stefanie Butland (Openscapes)
-   Eli Holmes (NMFS Open Science)

## Mentors

### FY25 Mentors

#### AFSC

Brian Fadely\
Josh London\
Em Markowitz\
Megsie Siple

#### NEFSC

Dan Pendleton

#### NWFSC

Eli Holmes\
Jonathan Peake\
Brooke Hawkins\
Hem Nalini Mozaria-Luna\
Erin Steiner\
Loren Stearman\
Dawn URycki

#### OST

Elizabeth Perl\
Kathryn Doering\
Sophie Breitbart

#### PIFSC

Yvonne Barkley\
Amanda Bradford\
Jon Brodziak\
Devin Johnson\
Jennifer McCullough\
Eva Schemmel\
Marylou Staman\
Phoebe Woodworth-Jefcoats

#### SEFSC

Carissa Gervasi\
Matt Grossi\
Adyan Rios\
Molly Stevens\
Ana Vaz

#### SWFSC

Alice Beittel\
Kourtney Burger\
Lynn deWitt\
Shannon Rankin\
Kevin Stierhoff

### FY24 Mentors

#### AFSC

Anna Abelman\
Jennifer Bigman\
Millie Brower\
Brian Fadely\
Craig Faunce\
Shannon Hennessey\
Kristin Holsman\
Stacie Koslovsky\
Josh London\
Em Markowitz\
Tony Orr\
Jonathan Richar\
Erin Richmond\
Megsie Siple\
Rod Towell\
Ben Williams\
Nancy Young

#### AKRO

Craig Millard

#### NEFSC

Laura Gruenburg\
Andrew Jones\
Julie Rose

#### NWFSC

Monica Diaz\
Eli Holmes\
Hem Nalini Mozaria-Luna\
Erin Steiner\
Nick Tolimieri\
Eric Ward\
Greg Williams

#### OST

Kathryn Doering\
Elizabeth Perl\
Christine Stawitz

#### PIFSC

Yvonne Barkley\
Amanda Bradford\
Jon Brodziak\
Devin Johnson\
Lori Luers\
Michael Marsik\
Meg Oshima\
Eva Schemmel\
Juliette Verstaen\
Phoebe Woodworth-Jefcoats

#### SEFSC

Matt Grossi\
Adyan Rios\
Molly Stevens\
Ana Vaz\
Lee Weinberger

#### SWFSC

Lynn deWitt\
Carissa Gervasi\
Dale Robinson\
Kevin Stierhoff

#### SWFSC/PIFSC

Sunny Hospital

### FY23 Mentors

#### AFSC

Josh London\
Em Markowitz\
Megsie Siple

#### AKRO

Craig Millard

#### NEFSC

Andrew Jones\
Scott Large

#### NWFSC

Eli Holmes\
Erin Steiner\
Eric Ward

#### OST

Kathryn Doering\
Elizabeth Perl\
Christine Stawitz

#### PIFSC

Amanda Bradford\
Juliette Verstaen

#### SEFSC

Adyan Rios\
Molly Stevens

#### SWFSC

Kevin Stierhoff
